### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by hbsage** [benjamingli/Electric-Load-Forecasting#1]
您好，我毕业设计是电量预测相关的，请问你的数据是怎么得到的，能否留个邮箱，想咨询一些问题，谢谢！

**Comment by zhouseeyou** [comment]
您好，请问您的数据可否公开，或者方便发我一份吗？我的邮箱 770885521@qq.com，谢谢！

**Comment by winnerwong** [comment]
请问你的主要参考文献是啥

**Comment by codebao** [comment]
您好，请问您的数据可否公开，或者方便发我一份吗？我的邮箱 2371512702@qq.com，谢谢！

**Comment by tsueseong** [comment]
您好，是否方便发一份数据集，邮箱544460209@qq.com,跪谢大佬

**Comment by hulingyue** [comment]
您好，是否方便发一份数据集，邮箱511809125@qq.com,跪谢大佬

**Comment by benjamingli** [comment]
不好意思，数据集是保密的，不可以给大家，请大家有条件的找相关国网单位获取，或使用kaggle捷克斯洛伐克公开数据集。天气条件数据可以自行在天气网站爬取。

**Comment by hulingyue** [comment]
好吧，依然谢谢你




------------------ 原始邮件 ------------------
发件人: "Songling Li"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 上午10:41
收件人: "benjamingli/Electric-Load-Forecasting"<Electric-Load-Forecasting@noreply.github.com>;
抄送: "511809125"<511809125@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [benjamingli/Electric-Load-Forecasting] 数据问题 (#1)




不好意思，数据集是保密的，不可以给大家，请大家有条件的找相关国网单位获取，或使用kaggle捷克斯洛伐克公开数据集。天气条件数据可以自行在天气网站爬取。
